###
GET http://localhost:5000

### all products
GET http://localhost:5000/api/products

###create

POST http://localhost:5000/api/products
Content-Type: application/json

{
  "name": "Phone Model Y",
  "description": "A great product for testing.",
  "price": 99.99,
  "category": "Electronics",
  "inStock": true,
  "sku": "SKU1235"
}
### get product by id
GET http://localhost:5000/api/products/684c05731e0c39356596966f

### update product by id
PUT http://localhost:5000/api/products/684c05731e0c39356596966f
Content-Type: application/json

{
  "name": "Phone Model XYZ",
  "description": "An updated description.",
  "price": 89.99,
  "category": "Electronics",
  "inStock": false,
  "sku": "SKU12356"
}

### delete product by id
DELETE http://localhost:5000/api/products/684c05901e0c393565969672