###
GET http://localhost:5000

### all products
GET http://localhost:5000/api/products

###create

POST http://localhost:5000/api/products
Content-Type: application/json

{
  "name": "PS2",
  "description": "A great product for testing.",
  "price": 299.99,
  "category": "Electronics",
  "stock": 10,
  "sku": "SKU99"
}
### get product by id
GET http://localhost:5000/api/products/684c05731e0c39356596966f

### update product by id
PUT http://localhost:5000/api/products/6852cad3818f6bf74e3b63de
Content-Type: application/json

{
  "name": "PS%",
  "description": "Gaming Console",
  "price": 199.99,
  "category": "Electronics",
  "stock": 10,
  "sku": "SKU1"
}

### delete product by id
DELETE http://localhost:5000/api/products/684c05901e0c393565969672