### Register a new user Workflow for placing an Order
POST http://localhost:5001/api/users/register
Content-Type: application/json

{
    "username": "justing thomas",
    "password": "dhruv123",
    "email": "justingthomas@example.com",
    "firstname": "Justin",
    "lastname": "Thomas"
}
### Login a user
POST http://localhost:5001/api/users/login
Content-Type: application/json

{
    "username": "justing thomas",
    "password": "dhruv123"
}

###Product Browsing
GET http://localhost:5000/api/products

###Placing an order
POST http://localhost:5002/api/orders
Content-Type: application/json
Authorization:

{
  "products": [
    { "productId": "684c05731e0c39356596966f", "quantity": 2 },
    { "productId": "684c05c81e0c393565969677", "quantity": 2 }
  ]
}
