### Register a new user
POST http://localhost:5001/api/users/register
Content-Type: application/json

{
    "username": "justing thomas",
    "password": "dhruv123",
    "email": "justingthomas@example.com",
    "firstname": "Justin",
    "lastname": "Thomas"
}
### Login a user
POST http://localhost:5001/api/users/login
Content-Type: application/json

{
    "username": "justing thomas",
    "password": "dhruv123"
}
### Get User Profile
GET http://localhost:5001/api/users/profile
Content-Type: application/json

### Update User Profile
PUT http://localhost:5001/api/users/profile
Content-Type: application/json

{
    "username": "justin thomas",
    "email": "justingthomas@example.com",
    "firstName": "Justin",
    "lastName": "Thomas"
}
